version: '3'
services:
    apache:
        build: .docker/apache
        container_name: seodash_apache
        ports:
          - 8080:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/seodash2
        depends_on:
          - php
          - mysql

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: seodash_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: seodash2
            MYSQL_USER: seodash2
            MYSQL_PASSWORD: seodash2

    php:
        build: .docker/php
        container_name: seodash_php
        volumes:
          - .:/home/wwwroot/seodash2
        environment:
          - maildev_host=seodash_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: seodash_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8000:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: seodash_maildev
        ports:
          - 8001:80
